{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 1, "revision": 4, "architecture": "arm64" },
    "classnamespace": "box",
    "rect": [100.0, 100.0, 1050.0, 650.0],
    "openinpresentation": 0,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "boxes": [
      { "box": { "id": "title", "maxclass": "comment", "text": "viture.ultra — native Luma Ultra tracking for Max 9", "fontsize": 20.0, "patching_rect": [30.0, 20.0, 560.0, 30.0] } },
      { "box": { "id": "connect", "maxclass": "message", "text": "connect", "patching_rect": [30.0, 80.0, 65.0, 22.0] } },
      { "box": { "id": "disconnect", "maxclass": "message", "text": "disconnect", "patching_rect": [105.0, 80.0, 78.0, 22.0] } },
      { "box": { "id": "recenter", "maxclass": "message", "text": "recenter", "patching_rect": [195.0, 80.0, 66.0, 22.0] } },
      { "box": { "id": "reset", "maxclass": "message", "text": "reset", "patching_rect": [270.0, 80.0, 45.0, 22.0] } },
      { "box": { "id": "rate", "maxclass": "message", "text": "rate 120", "patching_rect": [330.0, 80.0, 65.0, 22.0] } },
      { "box": { "id": "bang", "maxclass": "button", "patching_rect": [410.0, 80.0, 24.0, 24.0] } },
      { "box": { "id": "brightness", "maxclass": "message", "text": "brightness 5", "patching_rect": [465.0, 80.0, 85.0, 22.0] } },
      { "box": { "id": "volume", "maxclass": "message", "text": "volume 5", "patching_rect": [560.0, 80.0, 65.0, 22.0] } },
      { "box": { "id": "film", "maxclass": "message", "text": "film 1.", "patching_rect": [635.0, 80.0, 52.0, 22.0] } },
      { "box": { "id": "getstate", "maxclass": "message", "text": "getstate", "patching_rect": [697.0, 80.0, 64.0, 22.0] } },
      { "box": { "id": "displaymode", "maxclass": "message", "text": "displaymode 1200p60", "patching_rect": [30.0, 115.0, 145.0, 22.0] } },
      { "box": { "id": "dimension", "maxclass": "message", "text": "dimension 0", "patching_rect": [185.0, 115.0, 82.0, 22.0] } },
      { "box": { "id": "dutycycle", "maxclass": "message", "text": "dutycycle 98", "patching_rect": [277.0, 115.0, 88.0, 22.0] } },
      { "box": { "id": "autoexposure", "maxclass": "message", "text": "autoexposure", "patching_rect": [375.0, 115.0, 88.0, 22.0] } },
      { "box": { "id": "exposure", "maxclass": "message", "text": "exposure 4. 4", "patching_rect": [473.0, 115.0, 92.0, 22.0] } },
      { "box": { "id": "external", "maxclass": "newobj", "text": "viture.ultra 120", "patching_rect": [30.0, 155.0, 110.0, 22.0] } },
      { "box": { "id": "route", "maxclass": "newobj", "text": "route pose euler imu vsync tracking_stable stereo state brightness volume display_mode film dutycycle worn connected alive device product_id sdk_version firmware recentered reset dropped sdklog control error rate", "patching_rect": [30.0, 205.0, 1000.0, 22.0] } },
      { "box": { "id": "pose-label", "maxclass": "comment", "text": "pose: px py pz qw qx qy qz status timestamp", "patching_rect": [30.0, 240.0, 330.0, 22.0] } },
      { "box": { "id": "pose", "maxclass": "message", "text": "", "patching_rect": [30.0, 270.0, 430.0, 22.0] } },
      { "box": { "id": "euler-label", "maxclass": "comment", "text": "euler: roll pitch yaw timestamp", "patching_rect": [500.0, 240.0, 250.0, 22.0] } },
      { "box": { "id": "euler", "maxclass": "message", "text": "", "patching_rect": [500.0, 270.0, 350.0, 22.0] } },
      { "box": { "id": "imu-label", "maxclass": "comment", "text": "imu: ax ay az gx gy gz timestamp", "patching_rect": [30.0, 335.0, 270.0, 22.0] } },
      { "box": { "id": "imu", "maxclass": "message", "text": "", "patching_rect": [30.0, 365.0, 430.0, 22.0] } },
      { "box": { "id": "other-label", "maxclass": "comment", "text": "other messages", "patching_rect": [500.0, 335.0, 150.0, 22.0] } },
      { "box": { "id": "other", "maxclass": "message", "text": "", "patching_rect": [500.0, 365.0, 430.0, 22.0] } },
      { "box": { "id": "note", "maxclass": "comment", "text": "OpenGL coordinates: +X right, +Y up, +Z backward. status 0 = stable. Only one object may connect at once.", "patching_rect": [30.0, 455.0, 720.0, 22.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["connect", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["disconnect", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["recenter", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["reset", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["rate", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["bang", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["brightness", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["volume", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["film", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["getstate", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["displaymode", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["dimension", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["dutycycle", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["autoexposure", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["exposure", 0], "destination": ["external", 0] } },
      { "patchline": { "source": ["external", 0], "destination": ["route", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["pose", 1] } },
      { "patchline": { "source": ["route", 1], "destination": ["euler", 1] } },
      { "patchline": { "source": ["route", 2], "destination": ["imu", 1] } },
      { "patchline": { "source": ["route", 3], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 4], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 5], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 6], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 7], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 8], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 9], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 10], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 11], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 12], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 13], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 14], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 15], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 16], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 17], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 18], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 19], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 20], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 21], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 22], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 23], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 24], "destination": ["other", 1] } },
      { "patchline": { "source": ["route", 25], "destination": ["other", 1] } }
    ]
  }
}
